// === ALLNERA PARK PRESENTS: DINO OF THE DAY ===

// Wave 1 🦕
const dinoList = [
  { name: "AARDONYX", fact: "A transitional dinosaur between early bipeds and giant sauropods.", wiki: "https://en.wikipedia.org/wiki/Aardonyx" },
  { name: "ABELISAURUS", fact: "A large carnivorous dinosaur from South America with short, bulldog-like skull.", wiki: "https://en.wikipedia.org/wiki/Abelisaurus" },
  { name: "ANCHELOUSAURUS", fact: "A hornless relative of Triceratops with a rough boss on its nose.", wiki: "https://en.wikipedia.org/wiki/Achelousaurus" },
  { name: "ACHILLOBATOR", fact: "A raptor with massive claws and strong legs named after Achilles.", wiki: "https://en.wikipedia.org/wiki/Achillobator" },
  { name: "ACROCANTHOSAURUS", fact: "Recognized by tall neural spines that formed a ridge along its back.", wiki: "https://en.wikipedia.org/wiki/Acrocanthosaurus" },
  { name: "AEGYPTOSAURUS", fact: "A long-necked dinosaur from Egypt, destroyed during WWII bombings.", wiki: "https://en.wikipedia.org/wiki/Aegyptosaurus" },
  { name: "AFROVENATOR", fact: "One of Africa’s most complete theropods; name means 'African hunter.'", wiki: "https://en.wikipedia.org/wiki/Afrovenator" },
  { name: "AGILISAURUS", fact: "A small, agile herbivore that could sprint on two legs.", wiki: "https://en.wikipedia.org/wiki/Agilisaurus" },
  { name: "ALAMOSAURUS", fact: "One of the last sauropods before the extinction event.", wiki: "https://en.wikipedia.org/wiki/Alamosaurus" },
  { name: "ALBERTACERATOPS", fact: "A horned dinosaur with long brow horns similar to Triceratops.", wiki: "https://en.wikipedia.org/wiki/Albertaceratops" },
  { name: "ALBERTOSAURUS", fact: "A close relative of T. rex but smaller and faster.", wiki: "https://en.wikipedia.org/wiki/Albertosaurus" },
  { name: "ALECTROSAURUS", fact: "A lesser-known Asian tyrannosauroid with long limbs built for speed.", wiki: "https://en.wikipedia.org/wiki/Alectrosaurus" },
  { name: "ALIORAMUS", fact: "A long-snouted tyrannosaur known from Mongolia.", wiki: "https://en.wikipedia.org/wiki/Alioramus" },
  { name: "ALLOSAURUS", fact: "The best dinosaur. Jacob's favorite. An apex predator of the Late Jurassic; sleek, strong, and efficient.", wiki: "https://en.wikipedia.org/wiki/Allosaurus" },
  { name: "ALVAREZSAURUS", fact: "A tiny dinosaur with one giant claw per hand, possibly for digging insects.", wiki: "https://en.wikipedia.org/wiki/Alvarezsaurus" },
  { name: "AMARGASAURUS", fact: "Had twin rows of spines along its neck that may have supported a sail.", wiki: "https://en.wikipedia.org/wiki/Amargasaurus" },
  { name: "AMMOSAURUS", fact: "A small plant-eater that may have walked on two or four legs.", wiki: "https://en.wikipedia.org/wiki/Ammosaurus" },
  { name: "AMPELOSAURUS", fact: "A European sauropod covered in armor-like osteoderms.", wiki: "https://en.wikipedia.org/wiki/Ampelosaurus" },
  { name: "AMYGDALODON", fact: "One of the earliest known sauropods from South America.", wiki: "https://en.wikipedia.org/wiki/Amygdalodon" },
  { name: "ANCHICERATOPS", fact: "Had a large frill with ornate ridges and two long brow horns.", wiki: "https://en.wikipedia.org/wiki/Anchiceratops" },
  { name: "ANCHIORNIS", fact: "A feathered dinosaur that could glide before true flight evolved.", wiki: "https://en.wikipedia.org/wiki/Anchiornis" },
  { name: "ANCHISAURUS", fact: "One of the earliest plant-eating dinosaurs, small and lightweight.", wiki: "https://en.wikipedia.org/wiki/Anchisaurus" },
  { name: "ANKYLOSAURUS", fact: "The living tank of the Late Cretaceous, armored and wielding a tail club.", wiki: "https://en.wikipedia.org/wiki/Ankylosaurus" },
  { name: "ANSERIMIMUS", fact: "A fast, ostrich-like dinosaur with strong arms and claws.", wiki: "https://en.wikipedia.org/wiki/Anserimimus" },
  { name: "ANTARCTOSAURUS", fact: "A sauropod discovered in South America, despite its icy name.", wiki: "https://en.wikipedia.org/wiki/Antarctosaurus" },
  { name: "APATOSAURUS", fact: "Once mixed up with Brontosaurus; its neck vertebrae were massive.", wiki: "https://en.wikipedia.org/wiki/Apatosaurus" },
  { name: "AQUILOPS", fact: "The earliest known horned dinosaur in North America.", wiki: "https://en.wikipedia.org/wiki/Aquilops" },
  { name: "ARAGOSAURUS", fact: "A large plant-eater from Spain’s Early Cretaceous.", wiki: "https://en.wikipedia.org/wiki/Aragosaurus" },
  { name: "ARALOSAURUS", fact: "A hadrosaur with a bony crest, discovered in Kazakhstan.", wiki: "https://en.wikipedia.org/wiki/Aralosaurus" },
  { name: "ARCHAEOCERATOPS", fact: "An early ceratopsian showing the first steps toward horns.", wiki: "https://en.wikipedia.org/wiki/Archaeoceratops" },
  { name: "ARCHAEORNITHOMIMUS", fact: "An ostrich-like dinosaur with long legs for sprinting across floodplains.", wiki: "https://en.wikipedia.org/wiki/Archaeornithomimus" },
  { name: "ARGENTINOSAURUS", fact: "One of the largest known land animals, possibly over 100 feet long.", wiki: "https://en.wikipedia.org/wiki/Argentinosaurus" },
  { name: "ARRHINOCERATOPS", fact: "A horned dinosaur with a short nasal horn and decorative frill.", wiki: "https://en.wikipedia.org/wiki/Arrhinoceratops" },
  { name: "ATLASCOPCOSAURUS", fact: "A small herbivorous dinosaur from Australia named after a mining company.", wiki: "https://en.wikipedia.org/wiki/Atlascopcosaurus" },
  { name: "ATROCIRAPTOR", fact: "A stocky, fierce dromaeosaur known for its short, powerful snout.", wiki: "https://en.wikipedia.org/wiki/Atrociraptor" },
  { name: "AUCASAURUS", fact: "A one-ton abelisaurid with tiny arms and a massive head, found in Argentina.", wiki: "https://en.wikipedia.org/wiki/Aucasaurus" },
  { name: "AUSTROSAURUS", fact: "An Australian sauropod that helped confirm dinosaurs lived on every continent.", wiki: "https://en.wikipedia.org/wiki/Austrosaurus" },
  { name: "AVACERATOPS", fact: "A small, early ceratopsian with a short frill and modest horns.", wiki: "https://en.wikipedia.org/wiki/Avaceratops" },
  { name: "AVIMIMUS", fact: "A birdlike dinosaur with feathers and long legs, possibly omnivorous.", wiki: "https://en.wikipedia.org/wiki/Avimimus" },
  { name: "BACTROSAURUS", fact: "A hadrosaur from China with a bony ridge along its back.", wiki: "https://en.wikipedia.org/wiki/Bactrosaurus" },
  { name: "BAGACERATOPS", fact: "A tiny, early horned dinosaur about the size of a turkey.", wiki: "https://en.wikipedia.org/wiki/Bagaceratops" },
  { name: "BAMBIRAPTOR", fact: "A small, intelligent raptor that may have hunted in packs.", wiki: "https://en.wikipedia.org/wiki/Bambiraptor" },
  { name: "BARAPASAURUS", fact: "A massive Indian sauropod from the Early Jurassic.", wiki: "https://en.wikipedia.org/wiki/Barapasaurus" },
  { name: "BAROSAURUS", fact: "A long-necked sauropod that could rear up to reach treetops 50 feet high.", wiki: "https://en.wikipedia.org/wiki/Barosaurus" },
  { name: "BARYONYX", fact: "A fish-eating predator with a crocodile-like snout and a massive claw on each hand.", wiki: "https://en.wikipedia.org/wiki/Baryonyx" },
  { name: "BECKLESPINAX", fact: "A mysterious theropod known only from its spiny back vertebrae.", wiki: "https://en.wikipedia.org/wiki/Becklespinax" },
  { name: "BEIPIAOSAURUS", fact: "A feathered dinosaur with long arms and proto-feathers, bridging birds and theropods.", wiki: "https://en.wikipedia.org/wiki/Beipiaosaurus" },
  { name: "BELLUSAURUS", fact: "A small sauropod that lived in herds during the Middle Jurassic.", wiki: "https://en.wikipedia.org/wiki/Bellusaurus" },
  { name: "BOROGOVIA", fact: "A long-legged troodontid named after a creature from Lewis Carroll’s poem.", wiki: "https://en.wikipedia.org/wiki/Borogovia" },
  { name: "BRACHIOSAURUS", fact: "The classic long-necked giant with giraffe-like posture and enormous lungs.", wiki: "https://en.wikipedia.org/wiki/Brachiosaurus" },
  { name: "BRACHYLOPHOSAURUS", fact: "A duck-billed dinosaur with a flat, paddle-like crest on its head.", wiki: "https://en.wikipedia.org/wiki/Brachylophosaurus" },
  { name: "BRACHYTRACHELOPAN", fact: "A short-necked sauropod — basically the opposite of a Diplodocus.", wiki: "https://en.wikipedia.org/wiki/Brachytrachelopan" },
  { name: "BUITRERAPTOR", fact: "A long-snouted raptor with needle teeth for catching small prey.", wiki: "https://en.wikipedia.org/wiki/Buitreraptor" },
  { name: "CAMARASAURUS", fact: "A sturdy sauropod with a boxy skull and spoon-shaped teeth.", wiki: "https://en.wikipedia.org/wiki/Camarasaurus" },
  { name: "CAMPTOSAURUS", fact: "A plant-eating ornithopod with strong legs for speed and defense.", wiki: "https://en.wikipedia.org/wiki/Camptosaurus" },
  { name: "CARCHARODONTOSAURUS", fact: "A shark-toothed giant that rivaled T. rex in size.", wiki: "https://en.wikipedia.org/wiki/Carcharodontosaurus" },
  { name: "CARNOTAURUS", fact: "A horned, fast-running predator with absurdly tiny arms.", wiki: "https://en.wikipedia.org/wiki/Carnotaurus" },
  { name: "CAUDIPTERYX", fact: "A peacock-like feathered dinosaur with a fan tail.", wiki: "https://en.wikipedia.org/wiki/Caudipteryx" },
  { name: "CEDARPELTA", fact: "A large, primitive ankylosaur armored from head to tail.", wiki: "https://en.wikipedia.org/wiki/Cedarpelta" },
  { name: "CENTROSAURUS", fact: "A horned dinosaur with a massive nasal horn and spiked frill.", wiki: "https://en.wikipedia.org/wiki/Centrosaurus" },
    { name: "CERATOSAURUS", fact: "A horned carnivore with blade-like teeth and a single nasal horn used for display.", wiki: "https://en.wikipedia.org/wiki/Ceratosaurus" },
  { name: "CETIOSAURISCUS", fact: "A Middle Jurassic sauropod once mistaken for a sea monster.", wiki: "https://en.wikipedia.org/wiki/Cetiosauriscus" },
  { name: "CETIOSAURUS", fact: "Nicknamed the 'whale lizard' for its massive size and river habitat.", wiki: "https://en.wikipedia.org/wiki/Cetiosaurus" },
  { name: "CHAOYANGSAURUS", fact: "An early ceratopsian from China, showing the beginnings of the horned dinosaur lineage.", wiki: "https://en.wikipedia.org/wiki/Chaoyangsaurus" },
  { name: "CHASMOSAURUS", fact: "A horned dinosaur with a wide, ornate frill full of openings.", wiki: "https://en.wikipedia.org/wiki/Chasmosaurus" },
  { name: "CHINDESAURUS", fact: "One of the oldest known dinosaurs, a small early predator from Arizona.", wiki: "https://en.wikipedia.org/wiki/Chindesaurus" },
  { name: "CHINSHAKIANGOSAURUS", fact: "A rare sauropod known from only a few bones in China’s Jurassic beds.", wiki: "https://en.wikipedia.org/wiki/Chinshakiangosaurus" },
  { name: "CHIROSTENOTES", fact: "A birdlike dinosaur with grasping hands and long feathers.", wiki: "https://en.wikipedia.org/wiki/Chirostenotes" },
  { name: "CHUBUTISAURUS", fact: "A medium-sized sauropod that lived in Argentina’s lush Cretaceous forests.", wiki: "https://en.wikipedia.org/wiki/Chubutisaurus" },
  { name: "CHUNGKINGOSAURUS", fact: "An armored dinosaur with spines running down its back and tail.", wiki: "https://en.wikipedia.org/wiki/Chungkingosaurus" },
  { name: "CITIPATI", fact: "An oviraptor found sitting on its nest, proving they brooded like birds.", wiki: "https://en.wikipedia.org/wiki/Citipati" },
  { name: "COELOPHYSIS", fact: "A slender, fast predator and one of the earliest known theropods.", wiki: "https://en.wikipedia.org/wiki/Coelophysis" },
  { name: "COELURUS", fact: "A small, lightweight carnivore that helped define the Coelurosauria group.", wiki: "https://en.wikipedia.org/wiki/Coelurus" },
  { name: "COLORADISAURUS", fact: "A prosauropod from Argentina known for its strong hind legs and plant diet.", wiki: "https://en.wikipedia.org/wiki/Coloradisaurus" },
  { name: "COMPSOGNATHUS", fact: "A chicken-sized predator often found fossilized whole.", wiki: "https://en.wikipedia.org/wiki/Compsognathus" },
  { name: "CONCAVENATOR", fact: "A Spanish theropod with a mysterious hump on its back, possibly for display.", wiki: "https://en.wikipedia.org/wiki/Concavenator" },
  { name: "CONCHORAPTOR", fact: "An oviraptorid whose name means 'shell thief,' though it probably ate eggs and insects.", wiki: "https://en.wikipedia.org/wiki/Conchoraptor" },
  { name: "CONFUCIUSORNIS", fact: "One of the first birds with a beak, named after Confucius.", wiki: "https://en.wikipedia.org/wiki/Confuciusornis" },
  { name: "CORYTHOSAURUS", fact: "A duck-billed dinosaur with a helmet-like crest used for sound resonance.", wiki: "https://en.wikipedia.org/wiki/Corythosaurus" },
  { name: "CRYOLOPHOSAURUS", fact: "The 'Elvisaurus' — named for its pompadour-like crest.", wiki: "https://en.wikipedia.org/wiki/Cryolophosaurus" },
  { name: "DACENTRURUS", fact: "An early stegosaur with large shoulder spikes and a broad back.", wiki: "https://en.wikipedia.org/wiki/Dacentrurus" },
  { name: "DASPLETOSAURUS", fact: "A muscular tyrannosaurid — the literal warm-up act for T. rex.", wiki: "https://en.wikipedia.org/wiki/Daspletosaurus" },
  { name: "DATOUSAURUS", fact: "A Jurassic sauropod with spoon-shaped teeth for stripping vegetation.", wiki: "https://en.wikipedia.org/wiki/Datousaurus" },
  { name: "DEINOCHEIRUS", fact: "The 'terrible hands' dinosaur, later revealed to be a goofy-looking giant duck-armed omnivore.", wiki: "https://en.wikipedia.org/wiki/Deinocheirus" },
  { name: "DEINONYCHUS", fact: "The sickle-clawed raptor that inspired *Jurassic Park*’s Velociraptors.", wiki: "https://en.wikipedia.org/wiki/Deinonychus" },
  { name: "DELTADROMEUS", fact: "A sleek African carnivore built for high-speed pursuit.", wiki: "https://en.wikipedia.org/wiki/Deltadromeus" },
  { name: "DICRAEOSAURUS", fact: "A short-necked sauropod with paired spines along its vertebrae.", wiki: "https://en.wikipedia.org/wiki/Dicraeosaurus" },
  { name: "DILOPHOSAURUS", fact: "A double-crested predator — no venom, but pure Jurassic swagger.", wiki: "https://en.wikipedia.org/wiki/Dilophosaurus" },
  { name: "DIPLODOCUS", fact: "A whip-tailed sauropod that may have cracked its tail like a sonic boom.", wiki: "https://en.wikipedia.org/wiki/Diplodocus" },
  { name: "DRACOREX", fact: "Named 'Dragon King of Hogwarts' for its horned, spiky skull.", wiki: "https://en.wikipedia.org/wiki/Dracorex" },
  { name: "DREADNOUGHTUS", fact: "One of the heaviest land animals ever — name means 'fears nothing.'", wiki: "https://en.wikipedia.org/wiki/Dreadnoughtus" },
  { name: "DROMAEOSAURUS", fact: "A stocky, powerful raptor — all muscle and murder.", wiki: "https://en.wikipedia.org/wiki/Dromaeosaurus" },
  { name: "DROMICEIOMIMUS", fact: "An ostrich-like dinosaur whose name literally means 'emu mimic.'", wiki: "https://en.wikipedia.org/wiki/Dromiceiomimus" },
  { name: "DRYOSAURUS", fact: "A small, fast herbivore with strong hind legs for bounding through forests.", wiki: "https://en.wikipedia.org/wiki/Dryosaurus" },
  { name: "DRYPTOSAURUS", fact: "An early tyrannosauroid with long arms and wicked claws.", wiki: "https://en.wikipedia.org/wiki/Dryptosaurus" },
  { name: "DUBREUILLOSAURUS", fact: "A medium-sized European predator with a long, low skull.", wiki: "https://en.wikipedia.org/wiki/Dubreuillosaurus" },
    { name: "EDMONTONIA", fact: "A tank-like ankylosaur covered in bony plates and shoulder spikes.", wiki: "https://en.wikipedia.org/wiki/Edmontonia" },
  { name: "EDMONTOSAURUS", fact: "A large duck-billed herbivore from North America’s cold plains.", wiki: "https://en.wikipedia.org/wiki/Edmontosaurus" },
  { name: "EINIOSAURUS", fact: "A horned dinosaur with a forward-curving nose horn, like a unicorn with bad aim.", wiki: "https://en.wikipedia.org/wiki/Einiosaurus" },
  { name: "ELAPHROSAURUS", fact: "A lightweight carnivore whose name means 'light-footed lizard.'", wiki: "https://en.wikipedia.org/wiki/Elaphrosaurus" },
  { name: "EMAUSAURUS", fact: "An early armored dinosaur from Germany’s Jurassic coast.", wiki: "https://en.wikipedia.org/wiki/Emausaurus" },
  { name: "ENIGMACURSOR", fact: "A mysterious, poorly known dinosaur whose name literally means 'enigmatic runner.'", wiki: "https://en.wikipedia.org/wiki/Enigmacursor" },
  { name: "EOLAMBIA", fact: "One of the first duck-billed dinosaurs known from the Cretaceous of North America.", wiki: "https://en.wikipedia.org/wiki/Eolambia" },
  { name: "EORAPTOR", fact: "One of the earliest dinosaurs, small and nimble — a true Jurassic pioneer.", wiki: "https://en.wikipedia.org/wiki/Eoraptor" },
  { name: "EOTYRANNUS", fact: "An early relative of T. rex with feathers and long arms.", wiki: "https://en.wikipedia.org/wiki/Eotyrannus" },
  { name: "EQUIJUBUS", fact: "A duck-billed dinosaur from China whose name means 'horse mane.'", wiki: "https://en.wikipedia.org/wiki/Equijubus" },
  { name: "ERKETU", fact: "A sauropod with absurdly long neck vertebrae — the giraffe of dinosaurs.", wiki: "https://en.wikipedia.org/wiki/Erketu" },
  { name: "ERLIKOSAURUS", fact: "A sickle-clawed therizinosaur named after a Mongolian demon.", wiki: "https://en.wikipedia.org/wiki/Erlikosaurus" },
  { name: "EUHELOPUS", fact: "A Chinese sauropod with long forelimbs and a delicate skull.", wiki: "https://en.wikipedia.org/wiki/Euhelopus" },
  { name: "EUOPLOCEPHALUS", fact: "A club-tailed armored dinosaur — like an ancient wrecking ball with legs.", wiki: "https://en.wikipedia.org/wiki/Euoplocephalus" },
  { name: "EUROPASAURUS", fact: "A dwarf sauropod that evolved small size to survive on European islands.", wiki: "https://en.wikipedia.org/wiki/Europasaurus" },
  { name: "EUSTREPTOSPONDYLUS", fact: "A mid-sized Jurassic predator discovered by a teenage fossil hunter.", wiki: "https://en.wikipedia.org/wiki/Eustreptospondylus" },
  { name: "FUKUIRAPTOR", fact: "A raptor from Japan whose name means 'thief of Fukui.'", wiki: "https://en.wikipedia.org/wiki/Fukuiraptor" },
  { name: "FUKUISAURUS", fact: "A small herbivore also from Fukui, Japan — proving not all dinosaurs there were bitey.", wiki: "https://en.wikipedia.org/wiki/Fukuisaurus" },
  { name: "GALLIMIMUS", fact: "A speedy, ostrich-like dinosaur made famous by *Jurassic Park*.", wiki: "https://en.wikipedia.org/wiki/Gallimimus" },
  { name: "GARGOYLEOSAURUS", fact: "An early armored dinosaur named for its spooky, gargoyle-like skull.", wiki: "https://en.wikipedia.org/wiki/Gargoyleosaurus" },
  { name: "GARUDIMIMUS", fact: "A beaked, flightless omnivore named after a bird deity.", wiki: "https://en.wikipedia.org/wiki/Garudimimus" },
  { name: "GASOSAURUS", fact: "Discovered during the building of a gas plant — hence its name.", wiki: "https://en.wikipedia.org/wiki/Gasosaurus" },
  { name: "GASPARINISAURA", fact: "A small herbivore from Argentina named after paleontologist Zulma Gasparini.", wiki: "https://en.wikipedia.org/wiki/Gasparinisaura" },
  { name: "GASTONIA", fact: "A spiky ankylosaur named after the fossil hunter who found it, not the Disney hunk.", wiki: "https://en.wikipedia.org/wiki/Gastonia" },
  { name: "GIGANOTOSAURUS", fact: "A South American predator rivaling T. rex in size but probably faster.", wiki: "https://en.wikipedia.org/wiki/Giganotosaurus" },
  { name: "GIGANTORAPTOR", fact: "A massive, feathered oviraptor the size of a bus — terrifying but fabulous.", wiki: "https://en.wikipedia.org/wiki/Gigantoraptor" },
  { name: "GILMOREOSAURUS", fact: "A duck-billed dinosaur from Mongolia named after a pioneering American paleontologist.", wiki: "https://en.wikipedia.org/wiki/Gilmoreosaurus" },
  { name: "GIRAFFATITAN", fact: "Tallest of the tall — a brachiosaur relative that towered over the trees.", wiki: "https://en.wikipedia.org/wiki/Giraffatitan" },
  { name: "GOBISAURUS", fact: "A heavily armored ankylosaur discovered in Mongolia’s Gobi Desert.", wiki: "https://en.wikipedia.org/wiki/Gobisaurus" },
  { name: "GORGOSAURUS", fact: "A Canadian tyrannosaur that hunted hadrosaurs with terrifying efficiency.", wiki: "https://en.wikipedia.org/wiki/Gorgosaurus" },
  { name: "GOYOCEPHALE", fact: "A dome-headed dinosaur with spikes and a fantastic name.", wiki: "https://en.wikipedia.org/wiki/Goyocephale" },
  { name: "GRACILICERATOPS", fact: "A small, early relative of Triceratops with delicate horns.", wiki: "https://en.wikipedia.org/wiki/Graciliceratops" },
  { name: "GRYPOSAURUS", fact: "A hadrosaur with a hooked snout and one of the longest dinosaur noses ever.", wiki: "https://en.wikipedia.org/wiki/Gryposaurus" },
  { name: "GUAIBASAURUS", fact: "A small, early dinosaur that walked the line between carnivore and omnivore.", wiki: "https://en.wikipedia.org/wiki/Guaibasaurus" },
  { name: "GUANLONG", fact: "A feathered ancestor of T. rex with a dramatic head crest — nature’s theater kid.", wiki: "https://en.wikipedia.org/wiki/Guanlong" },
  { name: "HADROSAURUS", fact: "The first nearly complete dinosaur skeleton ever found in North America.", wiki: "https://en.wikipedia.org/wiki/Hadrosaurus" },
  { name: "HAGRYPHUS", fact: "An ostrich-like theropod with claws and sass, named for the Egyptian god of the sky.", wiki: "https://en.wikipedia.org/wiki/Hagryphus" },
  { name: "HAPLOCANTHOSAURUS", fact: "A gentle, long-necked sauropod with a lighter build than its cousins.", wiki: "https://en.wikipedia.org/wiki/Haplocanthosaurus" },
  { name: "HARPYMIMUS", fact: "A fast, bird-mimicking dinosaur that probably used its claws to dig for food.", wiki: "https://en.wikipedia.org/wiki/Harpymimus" },
  { name: "HERRERASAURUS", fact: "One of the oldest known dinosaurs — still figuring out the whole ‘being a dinosaur’ thing.", wiki: "https://en.wikipedia.org/wiki/Herrerasaurus" },
  { name: "HESPEROSAURUS", fact: "A close relative of Stegosaurus, with smaller plates and a chill disposition.", wiki: "https://en.wikipedia.org/wiki/Hesperosaurus" },
  { name: "HETERODONTOSAURUS", fact: "Had vampire teeth and a parrot beak — truly a fashion icon of the Early Jurassic.", wiki: "https://en.wikipedia.org/wiki/Heterodontosaurus" },
  { name: "HEYUANNIA", fact: "An oviraptor with a stylish crest and possible nesting instincts.", wiki: "https://en.wikipedia.org/wiki/Heyuannia" },
  { name: "HOMALOCEPHALE", fact: "A dome-headed dinosaur that might have used its flat skull for headbutting contests.", wiki: "https://en.wikipedia.org/wiki/Homalocephale" },
  { name: "HUAYANGOSAURUS", fact: "A small, early stegosaur with shoulder spikes for extra spice.", wiki: "https://en.wikipedia.org/wiki/Huayangosaurus" },
  { name: "HYLAEOSAURUS", fact: "One of the first armored dinosaurs ever discovered — basically an ancient tank.", wiki: "https://en.wikipedia.org/wiki/Hylaeosaurus" },
  { name: "HYPACROSAURUS", fact: "A duck-billed dinosaur with a hollow crest for booming honks.", wiki: "https://en.wikipedia.org/wiki/Hypacrosaurus" },
  { name: "HYPSILOPHODON", fact: "A small, speedy herbivore that could outrun most predators — the Jurassic track star.", wiki: "https://en.wikipedia.org/wiki/Hypsilophodon" },
  { name: "IGUANODON", fact: "One of the first dinosaurs ever named, famous for its thumb spikes.", wiki: "https://en.wikipedia.org/wiki/Iguanodon" },
  { name: "INDOSUCHUS", fact: "An Indian abelisaurid predator with a skull built for crunching bone.", wiki: "https://en.wikipedia.org/wiki/Indosuchus" },
  { name: "IRRITATOR", fact: "Named by annoyed scientists who received a fossil tampered with by fossil traders.", wiki: "https://en.wikipedia.org/wiki/Irritator" },
  { name: "ISAURUS", fact: "A dubious genus whose fossils turned out to belong to other dinosaurs — identity crisis energy.", wiki: "https://en.wikipedia.org/wiki/Isisaurus" },
  { name: "JANENSCHIA", fact: "A long-necked sauropod named for a German paleontologist who excavated Tendaguru Hill.", wiki: "https://en.wikipedia.org/wiki/Janenschia" },
  { name: "JAXARTOSAURUS", fact: "A hadrosaur from Central Asia with a mysterious crest shape.", wiki: "https://en.wikipedia.org/wiki/Jaxartosaurus" },
  { name: "JINGSHANOSAURUS", fact: "A transitional sauropodomorph that bridged prosauropods and true sauropods.", wiki: "https://en.wikipedia.org/wiki/Jingshanosaurus" },
  { name: "JINZHOUSAURUS", fact: "A feathered plant-eater from China with a long tail and birdlike features.", wiki: "https://en.wikipedia.org/wiki/Jinzhousaurus" },
  { name: "JOBARIA", fact: "A massive African sauropod that lived long after most of its kin went extinct.", wiki: "https://en.wikipedia.org/wiki/Jobaria" },
  { name: "JURAVENATOR", fact: "A small predator with preserved skin impressions — science’s favorite Jurassic lizard boy.", wiki: "https://en.wikipedia.org/wiki/Juravenator" },
  { name: "KENTROSAURUS", fact: "A stegosaur with back and tail spikes that basically said ‘come at me, bro.’", wiki: "https://en.wikipedia.org/wiki/Kentrosaurus" },
  { name: "KHAAN", fact: "An oviraptor named after Genghis Khan — the most intimidating dad joke in paleontology.", wiki: "https://en.wikipedia.org/wiki/Khaan" },
  { name: "KOTASAURUS", fact: "A primitive sauropod from India that helped define early giant evolution.", wiki: "https://en.wikipedia.org/wiki/Kotasaurus" },
  { name: "KRITOSAURUS", fact: "A duck-billed dinosaur whose name means 'noble lizard,' which feels a bit generous.", wiki: "https://en.wikipedia.org/wiki/Kritosaurus" },
  { name: "LAMBEOSAURUS", fact: "A crested hadrosaur with a head shaped like an axe blade.", wiki: "https://en.wikipedia.org/wiki/Lambeosaurus" },
  { name: "LAPPARENTOSAURUS", fact: "A mystery sauropod known from fragmentary remains in Madagascar.", wiki: "https://en.wikipedia.org/wiki/Lapparentosaurus" },
  { name: "LEAELLYNASAURA", fact: "A small polar dinosaur with huge eyes to see in winter darkness.", wiki: "https://en.wikipedia.org/wiki/Leaellynasaura" },
  { name: "LEPTOCERATOPS", fact: "A short-frilled horned dinosaur — small but mighty.", wiki: "https://en.wikipedia.org/wiki/Leptoceratops" },
  { name: "LESOTHOSAURUS", fact: "One of the earliest ornithischians — small, fast, and cute as hell.", wiki: "https://en.wikipedia.org/wiki/Lesothosaurus" },
  { name: "LIAOCERATOPS", fact: "An early ceratopsian that bridged the gap between small frills and Triceratops-sized drama.", wiki: "https://en.wikipedia.org/wiki/Liaoceratops" },
  { name: "LIGABUESAURUS", fact: "A sauropod named in honor of Italian paleontologist Giancarlo Ligabue.", wiki: "https://en.wikipedia.org/wiki/Ligabuesaurus" },
  { name: "LILIENSTERNUS", fact: "A German predator that ran like a greyhound and bit like a nightmare.", wiki: "https://en.wikipedia.org/wiki/Liliensternus" },
  { name: "LOPHORHOTHON", fact: "A primitive duck-billed dinosaur, possibly one of the earliest hadrosaurs.", wiki: "https://en.wikipedia.org/wiki/Lophorhothon" },
  { name: "LOPHOSTROPHEUS", fact: "A French carnivore that was small but efficient — like a prehistoric assassin.", wiki: "https://en.wikipedia.org/wiki/Lophostropheus" },
  { name: "LUFENGOSAURUS", fact: "A prosauropod from China that walked on two legs before sauropods went full quadruped.", wiki: "https://en.wikipedia.org/wiki/Lufengosaurus" },
  { name: "LURDUSAURUS", fact: "A bulky iguanodont built like a tank, one of the last of its kind.", wiki: "https://en.wikipedia.org/wiki/Lurdusaurus" },
  { name: "LUSOTITAN", fact: "Portugal’s pride — a massive sauropod towering over the Jurassic landscape.", wiki: "https://en.wikipedia.org/wiki/Lusotitan" },
  { name: "LYCORHINUS", fact: "An early ornithischian with long tusks — a vegetarian with attitude.", wiki: "https://en.wikipedia.org/wiki/Lycorhinus" },
  { name: "MAGYAROSAURUS", fact: "A dwarf sauropod that evolved small size to survive on islands.", wiki: "https://en.wikipedia.org/wiki/Magyarosaurus" },
  { name: "MAIASAURA", fact: "Known as the 'good mother lizard' for nesting colonies and parental care.", wiki: "https://en.wikipedia.org/wiki/Maiasaura" },
  { name: "MAJUNGASAURUS", fact: "A bone-crunching predator that may have practiced cannibalism.", wiki: "https://en.wikipedia.org/wiki/Majungasaurus" },
  { name: "MALAWISAURUS", fact: "One of the few sauropods known from Africa’s Early Cretaceous period.", wiki: "https://en.wikipedia.org/wiki/Malawisaurus" },
  { name: "MAMENCHISAURUS", fact: "Had one of the longest necks of any dinosaur — up to 15 meters long.", wiki: "https://en.wikipedia.org/wiki/Mamenchisaurus" },
  { name: "MAPUSAURUS", fact: "A giant carnivore closely related to Giganotosaurus, possibly hunting in packs.", wiki: "https://en.wikipedia.org/wiki/Mapusaurus" },
  { name: "MARSHOSAURUS", fact: "A mid-sized theropod from North America’s Morrison Formation.", wiki: "https://en.wikipedia.org/wiki/Marshosaurus" },
  { name: "MASIAKASAURUS", fact: "A small, sharp-toothed predator with a forward-jutting lower jaw.", wiki: "https://en.wikipedia.org/wiki/Masiakasaurus" },
  { name: "MASSOSPONDYLUS", fact: "An early herbivore that helped define the prosauropod lineage.", wiki: "https://en.wikipedia.org/wiki/Massospondylus" },
  { name: "MAXAKALISAURUS", fact: "A South American sauropod with bony armor — rare among its kind.", wiki: "https://en.wikipedia.org/wiki/Maxakalisaurus" },
  { name: "MEGALOSAURUS", fact: "The first dinosaur ever scientifically named — literally just 'big lizard.'", wiki: "https://en.wikipedia.org/wiki/Megalosaurus" },
  { name: "MELANOROSAURUS", fact: "A South African herbivore bridging the gap between early and true sauropods.", wiki: "https://en.wikipedia.org/wiki/Melanorosaurus" },
  { name: "METRIACANTHOSAURUS", fact: "A Jurassic predator whose name means 'moderately spined lizard.'", wiki: "https://en.wikipedia.org/wiki/Metriacanthosaurus" },
  { name: "MICROCERATUS", fact: "A tiny horned dinosaur — like a pocket-sized Triceratops.", wiki: "https://en.wikipedia.org/wiki/Microceratus" },
  { name: "MICROPACHYCEPHALOSAURUS", fact: "The smallest known dome-headed dinosaur, and the longest name in the fossil record.", wiki: "https://en.wikipedia.org/wiki/Micropachycephalosaurus" },
  { name: "MICRORAPTOR", fact: "A four-winged raptor that glided through Cretaceous forests.", wiki: "https://en.wikipedia.org/wiki/Microraptor" },
  { name: "MINMI", fact: "A small armored dinosaur that might have used belly armor to protect itself from attacks.", wiki: "https://en.wikipedia.org/wiki/Minmi" },
  { name: "MONOLOPHOSAURUS", fact: "A crested carnivore that ruled China’s Middle Jurassic period.", wiki: "https://en.wikipedia.org/wiki/Monolophosaurus" },
  { name: "MONONYKUS", fact: "Had a single large claw per hand, possibly used for digging.", wiki: "https://en.wikipedia.org/wiki/Mononykus" },
  { name: "MUSSAURUS", fact: "Originally known only from baby skeletons — hence 'mouse lizard.'", wiki: "https://en.wikipedia.org/wiki/Mussaurus" },
  { name: "MUTTABURRASAURUS", fact: "A stupid fucker that never deserved to live. Thank fuck for extinction.", wiki: "https://en.wikipedia.org/wiki/Muttaburrasaurus" },
  { name: "NANSHIUNGOSAURUS", fact: "A large therizinosaur with a long neck and huge claws, found in China.", wiki: "https://en.wikipedia.org/wiki/Nanshiungosaurus" },
  { name: "NEDOCERATOPS", fact: "A horned dinosaur so similar to Triceratops that scientists still argue if it's separate.", wiki: "https://en.wikipedia.org/wiki/Nedoceratops" },
  { name: "NEMEGTOSAURUS", fact: "A large sauropod from Mongolia’s Nemegt Formation.", wiki: "https://en.wikipedia.org/wiki/Nemegtosaurus" },
  { name: "NEOVENATOR", fact: "An agile, mid-sized predator from Europe — elegant but deadly.", wiki: "https://en.wikipedia.org/wiki/Neovenator" },
  { name: "NEUQUENSAURUS", fact: "A small, armored sauropod with unique tail vertebrae.", wiki: "https://en.wikipedia.org/wiki/Neuquensaurus" },
  { name: "NIGERSAURUS", fact: "Had a vacuum-shaped mouth with hundreds of tiny teeth — a prehistoric lawnmower.", wiki: "https://en.wikipedia.org/wiki/Nigersaurus" },
  { name: "NIPPONOSAURUS", fact: "Japan’s only known hadrosaur, discovered during WWII.", wiki: "https://en.wikipedia.org/wiki/Nipponosaurus" },
  { name: "NOASAURUS", fact: "A small South American predator with a unique claw on its foot.", wiki: "https://en.wikipedia.org/wiki/Noasaurus" },
  { name: "NODOSAURUS", fact: "A classic armored dinosaur with a clubless tail but serious defensive vibes.", wiki: "https://en.wikipedia.org/wiki/Nodosaurus" },
  { name: "NOMINGIA", fact: "An oviraptor with a pygostyle — the same tail bone modern birds use for tail feathers.", wiki: "https://en.wikipedia.org/wiki/Nomingia" },
  { name: "NOTHRONYCHUS", fact: "A feathered, pot-bellied herbivore with massive claws for grabbing vegetation.", wiki: "https://en.wikipedia.org/wiki/Nothronychus" },
  { name: "NQWEBASAURUS", fact: "A tiny, early coelurosaur nicknamed 'the pride of the Qwebe Valley.'", wiki: "https://en.wikipedia.org/wiki/Nqwebasaurus" },
  { name: "OMEISAURUS", fact: "A Chinese sauropod with one of the longest necks in the Jurassic — like, 30 feet of pure reach.", wiki: "https://en.wikipedia.org/wiki/Omeisaurus" },
  { name: "OPISTHOCELICAUDIA", fact: "A Mongolian sauropod with a strong tail and hollow vertebrae.", wiki: "https://en.wikipedia.org/wiki/Opisthocoelicaudia" },
  { name: "ORNITHOLESTES", fact: "A small, agile hunter that may have preyed on early birds.", wiki: "https://en.wikipedia.org/wiki/Ornitholestes" },
  { name: "ORNITHOMIMUS", fact: "An ostrich mimic — fast, feathered, and fabulous.", wiki: "https://en.wikipedia.org/wiki/Ornithomimus" },
  { name: "ORODROMEUS", fact: "A small, burrowing herbivore — one of the few dinosaurs that lived underground.", wiki: "https://en.wikipedia.org/wiki/Orodromeus" },
  { name: "ORYCTODROMEUS", fact: "Another tunneling herbivore that dug elaborate burrows — nature’s little mole-lizard.", wiki: "https://en.wikipedia.org/wiki/Oryctodromeus" },
  { name: "OTHNIELIA", fact: "Named after one of the most chaotic paleontologists in history, Othniel Marsh.", wiki: "https://en.wikipedia.org/wiki/Othnielia" },
  { name: "OURANOSAURUS", fact: "A sail-backed herbivore from Africa — basically a prehistoric camel with flair.", wiki: "https://en.wikipedia.org/wiki/Ouranosaurus" },
  { name: "OVIRAPTOR", fact: "Once thought to be an egg thief, now known to have been a devoted parent.", wiki: "https://en.wikipedia.org/wiki/Oviraptor" },
  { name: "PACHYCEPHALOSAURUS", fact: "The dome-headed 'bonehead' that may have used its skull for combat displays.", wiki: "https://en.wikipedia.org/wiki/Pachycephalosaurus" },
  { name: "PACHYRHINOSAURUS", fact: "A hornless ceratopsian with thick nasal bosses — the dinosaur equivalent of head armor.", wiki: "https://en.wikipedia.org/wiki/Pachyrhinosaurus" },
  { name: "PANO PLOSAURUS", fact: "A well-armored nodosaur that could shrug off most predators.", wiki: "https://en.wikipedia.org/wiki/Panoplosaurus" },
  { name: "PANTYDRACO", fact: "Named after the Pant-y-ffynnon quarry in Wales, not what you’re thinking.", wiki: "https://en.wikipedia.org/wiki/Pantydraco" },
  { name: "PARALITITAN", fact: "One of the largest dinosaurs ever discovered, found in Egypt’s tidal flats.", wiki: "https://en.wikipedia.org/wiki/Paralititan" },
  { name: "PARASAUROLOPHUS", fact: "Famous for its long crest, which acted as a resonance chamber for sound.", wiki: "https://en.wikipedia.org/wiki/Parasaurolophus" },
  { name: "PARKSOSAURUS", fact: "A small, nimble herbivore that likely lived near lakes and rivers.", wiki: "https://en.wikipedia.org/wiki/Parksosaurus" },
  { name: "PATAGOSAURUS", fact: "A sauropod from Patagonia that lived early in the Jurassic.", wiki: "https://en.wikipedia.org/wiki/Patagosaurus" },
  { name: "PATAGOTITAN", fact: "One of the heaviest creatures to ever walk the Earth — 70 tons of gentle power.", wiki: "https://en.wikipedia.org/wiki/Patagotitan" },
  { name: "PELECANIMIMUS", fact: "A beaked predator with over 200 teeth — which is way too many for one mouth.", wiki: "https://en.wikipedia.org/wiki/Pelecanimimus" },
  { name: "PELOROSAURUS", fact: "A sauropod known from fragmentary fossils — basically a prehistoric jigsaw puzzle.", wiki: "https://en.wikipedia.org/wiki/Pelorosaurus" },
  { name: "PENTACERATOPS", fact: "A five-horned dinosaur with the largest skull of any land animal.", wiki: "https://en.wikipedia.org/wiki/Pentaceratops" },
  { name: "PIATNITZK YSAURUS", fact: "A Jurassic predator from Argentina, one of the earliest known megalosaurs.", wiki: "https://en.wikipedia.org/wiki/Piatnitzkysaurus" },
  { name: "PINACOSAURUS", fact: "A Mongolian ankylosaur with a broad, armored body and tail club.", wiki: "https://en.wikipedia.org/wiki/Pinacosaurus" },
  { name: "PLATEOSAURUS", fact: "A long-necked plant-eater that dominated Late Triassic Europe.", wiki: "https://en.wikipedia.org/wiki/Plateosaurus" },
  { name: "PODOKESAURUS", fact: "A small carnivore known only from a single foot bone — talk about minimalism.", wiki: "https://en.wikipedia.org/wiki/Podokesaurus" },
  { name: "POEKILO PLEURON", fact: "A theropod whose name means 'varied ribs,' because paleontologists get weird with naming.", wiki: "https://en.wikipedia.org/wiki/Poekilopleuron" },
  { name: "POLACANTHUS", fact: "An armored dinosaur with spikes running down its back — the Jurassic porcupine.", wiki: "https://en.wikipedia.org/wiki/Polacanthus" },
  { name: "PRENOCEPHALE", fact: "A dome-headed dinosaur from Mongolia, possibly related to Pachycephalosaurus.", wiki: "https://en.wikipedia.org/wiki/Prenocephale" },
  { name: "PROBACTROSAURUS", fact: "An early iguanodontid that set the stage for the rise of hadrosaurs.", wiki: "https://en.wikipedia.org/wiki/Probactrosaurus" },
  { name: "PROCERATOSAURUS", fact: "A small predator with a bony crest — the punk phase of carnosaurs.", wiki: "https://en.wikipedia.org/wiki/Proceratosaurus" },
  { name: "PROCOMPSOGNATHUS", fact: "A chicken-sized carnivore best known for its cameo in Jurassic Park.", wiki: "https://en.wikipedia.org/wiki/Procompsognathus" },
  { name: "PROSAUROLOPHUS", fact: "A hadrosaur ancestor with a small head crest and a love for swamps.", wiki: "https://en.wikipedia.org/wiki/Prosaurolophus" },
  { name: "PROTARCHAEOPTERYX", fact: "A feathered, non-flying dinosaur from China — one of the earliest known with plumage.", wiki: "https://en.wikipedia.org/wiki/Protarchaeopteryx" },
  { name: "PROTOCERATOPS", fact: "UGLY. UGLY STUPID. UGLY FUCK. EW. KILL IT. NASTY. WHY THE FUCK IS IT DINOSAUR OF THE DAY?", wiki: "https://en.wikipedia.org/wiki/Protoceratops" },
  { name: "PROTOHADROS", fact: "A primitive hadrosaur that bridged iguanodonts and true duckbills.", wiki: "https://en.wikipedia.org/wiki/Protohadros" },
  { name: "PSITTACOSAURUS", fact: "A parrot-beaked herbivore that walked on two legs — ugly enough to be punted.", wiki: "https://en.wikipedia.org/wiki/Psittacosaurus" },
  { name: "PUERTASAURUS", fact: "A massive titanosaur known from Argentina — rivaled Argentinosaurus in size.", wiki: "https://en.wikipedia.org/wiki/Puertasaurus" },
  { name: "PYRORAPTOR", fact: "A fire-named raptor discovered after a forest blaze — fast, fierce, and fabulous.", wiki: "https://en.wikipedia.org/wiki/Pyroraptor" },
    { name: "QUAESITOSAURUS", fact: "A long-necked titanosaur from Mongolia with a weird, slightly squat skull.", wiki: "https://en.wikipedia.org/wiki/Quaesitosaurus" },
  { name: "RAJASAURUS", fact: "A robust Indian theropod with a deep skull and muscular build.", wiki: "https://en.wikipedia.org/wiki/Rajasaurus" },
  { name: "REBBACHISAURUS", fact: "A sauropod with distinctive low neural spines and unusual teeth adapted to stripping plants.", wiki: "https://en.wikipedia.org/wiki/Rebbachisaurus" },
  { name: "RHABDODON", fact: "A stocky European herbivore common in Late Cretaceous landscapes.", wiki: "https://en.wikipedia.org/wiki/Rhabdodon" },
  { name: "RHOETOSAURUS", fact: "An early sauropod from Australia known from fragmentary remains.", wiki: "https://en.wikipedia.org/wiki/Rhoetosaurus" },
  { name: "RINCHENIA", fact: "A relatively small pachycephalosaurid named after Mongolian paleontologist Rinchen.", wiki: "https://en.wikipedia.org/wiki/Rinchenia" },
  { name: "RIOJASAURUS", fact: "A South American sauropod with long forelimbs and a graceful neck.", wiki: "https://en.wikipedia.org/wiki/Riojasaurus" },
  { name: "RUGOPS", fact: "A short-snouted African theropod with a pitted skull—probably a scavenger or opportunistic hunter.", wiki: "https://en.wikipedia.org/wiki/Rugops" },
  { name: "SAICHANIA", fact: "An Asian ankylosaur with dense armor and a compact, squat body.", wiki: "https://en.wikipedia.org/wiki/Saichania" },
  { name: "SALTASAURUS", fact: "A small, armored titanosaur famous for osteoderms (bony armor) across its back.", wiki: "https://en.wikipedia.org/wiki/Saltasaurus" },
  { name: "SARCOsAURUS", fact: "A genus of early theropod; fragmentary remains have made its classification tricky.", wiki: "https://en.wikipedia.org/wiki/Sarcosaurus" },
  { name: "SAUROLOPHUS", fact: "A smooth-crested hadrosaur commonly found in North American and Asian deposits.", wiki: "https://en.wikipedia.org/wiki/Saurolophus" },
  { name: "SAUROPELTA", fact: "An ankylosaur-like armored dinosaur that used armor plates for defense.", wiki: "https://en.wikipedia.org/wiki/Sauropelta" },
  { name: "SAUROPHAGANAX", fact: "A giant Allosaurus-like predator, possibly one of the top carnivores in its ecosystem.", wiki: "https://en.wikipedia.org/wiki/Saurophaganax" },
  { name: "SAURORNITHOIDES", fact: "A nimble, birdlike troodontid with keen senses and grasping hands.", wiki: "https://en.wikipedia.org/wiki/Saurornithoides" },
  { name: "SCELIDOSAURUS", fact: "One of the earliest known armored dinosaurs with rows of bony scutes.", wiki: "https://en.wikipedia.org/wiki/Scelidosaurus" },
  { name: "SCUTELLOSAURUS", fact: "A tiny, lightly armored early ornithischian — the little cousin of the tank dinosaurs.", wiki: "https://en.wikipedia.org/wiki/Scutellosaurus" },
  { name: "SECERNOSAURUS", fact: "A hadrosauroid whose remains helped clarify duckbill evolution in South America.", wiki: "https://en.wikipedia.org/wiki/Secernosaurus" },
  { name: "SEGISAURUS", fact: "A small, early theropod known from a few distinctive leg bones.", wiki: "https://en.wikipedia.org/wiki/Segisaurus" },
  { name: "SEGNOSAURUS", fact: "A bizarre, long-clawed therizinosaurid that likely ate plants with terrifying efficiency.", wiki: "https://en.wikipedia.org/wiki/Segnosaurus" },
  { name: "SHAMOSAURUS", fact: "A stegosaurs-style dinosaur discovered in the Gobi with characteristic plates.", wiki: "https://en.wikipedia.org/wiki/Shamosaurus" },
  { name: "SHANAG", fact: "A small dromaeosaurid from Mongolia with gracile features and sharp claws.", wiki: "https://en.wikipedia.org/wiki/Shanag" },
  { name: "SHANTUNGOSAURUS", fact: "A large Chinese hadrosaur that once confused paleontologists with its size.", wiki: "https://en.wikipedia.org/wiki/Shantungosaurus" },
  { name: "SHUNOSAURUS", fact: "A lesser-known early sauropod; fragmentary remains make it a mystery genus.", wiki: "https://en.wikipedia.org/wiki/Shunosaurus" },
  { name: "SHUVUUIA", fact: "A tiny, owl-like predator with exceptional hearing adaptations for hunting at night.", wiki: "https://en.wikipedia.org/wiki/Shuvuuia" },
  { name: "SILVISAURUS", fact: "A small ornithopod from the Early Cretaceous with an agile build.", wiki: "https://en.wikipedia.org/wiki/Silvisaurus" },
  { name: "SINOCALLIOPTERYX", fact: "A feathered predator from China known for fossilized gut contents showing small prey items.", wiki: "https://en.wikipedia.org/wiki/Sinocalliopteryx" },
  { name: "SINORNITHOSAURUS", fact: "A feathered dromaeosaurid with evidence for complex plumage and possible venom or toxins.", wiki: "https://en.wikipedia.org/wiki/Sinornithosaurus" },
  { name: "SINOSAUROPTERYX", fact: "One of the first dinosaurs found with evidence of filamentous 'protofeathers.'", wiki: "https://en.wikipedia.org/wiki/Sinosauropteryx" },
  { name: "SINOVENATOR", fact: "An early troodontid that helps link troodontids to birdlike dinosaurs.", wiki: "https://en.wikipedia.org/wiki/Sinovenator" },
  { name: "SINRAPTOR", fact: "A formidable Jurassic predator from China closely related to Allosaurus-like theropods.", wiki: "https://en.wikipedia.org/wiki/Sinraptor" },
  { name: "SONIDOSAURUS", fact: "A sauropod with limited remains — adds to the diversity of Asian titanosaurs.", wiki: "https://en.wikipedia.org/wiki/Sonidosaurus" },
  { name: "SPICOMELLUS", fact: "A recently described armored ankylosaurid-like dinosaur with unusual osteoderm patterns.", wiki: "https://en.wikipedia.org/wiki/Spicomellus" },
  { name: "SPINOSAURUS", fact: "THE WATER LORD. A toothy, sail-backed juggernaut that hunted like a crocodile on steroids — fish, giant prey, coastal terror. One of Emma's faves.", wiki: "https://en.wikipedia.org/wiki/Spinosaurus" },
  { name: "STAURIKOSAURUS", fact: "An early saurischian from Brazil — small and primitive, but important for filling evolutionary gaps.", wiki: "https://en.wikipedia.org/wiki/Staurikosaurus" },
  { name: "STEGOCERAS", fact: "A dome-headed pachycephalosaur used for species recognition and possible head-butting.", wiki: "https://en.wikipedia.org/wiki/Stegoceras" },
  { name: "STEGOSAURUS", fact: "The plated, slow-moving herbivore with a spiked tail — iconic Jurassic armor and display plates.", wiki: "https://en.wikipedia.org/wiki/Stegosaurus" },
  { name: "STENONYCHOSAURUS", fact: "A small, birdlike troodontid with big eyes and a hunting habit of precision strikes.", wiki: "https://en.wikipedia.org/wiki/Stenonychosaurus" },
  { name: "STENOPELIX", fact: "A tiny ornithischian known from fragmentary cranial material — enigmatic and small.", wiki: "https://en.wikipedia.org/wiki/Stenopelix" },
  { name: "STRUTHIOMIMUS", fact: "A fast, toothless ornithomimid that likely used speed and herding as defense.", wiki: "https://en.wikipedia.org/wiki/Struthiomimus" },
  { name: "STRUTHIOSAURUS", fact: "A small, armored nodosaur — low-slung and covered in protective plates.", wiki: "https://en.wikipedia.org/wiki/Struthiosaurus" },
  { name: "STYGIMOLOCH", fact: "A dome-headed dinosaur with spikes on its skull, once thought to be a juvenile Pachycephalosaurus.", wiki: "https://en.wikipedia.org/wiki/Stygimoloch" },
  { name: "STYRACOSAURUS", fact: "A horned ceratopsian famed for its dramatic array of facial horns and frill spikes.", wiki: "https://en.wikipedia.org/wiki/Styracosaurus" },
  { name: "SUCHOMIMUS", fact: "A spinosaurid fish-eater with a long crocodile-like snout and massive thumb claw — a shoreline specialist.", wiki: "https://en.wikipedia.org/wiki/Suchomimus" },
  { name: "SUPERSAURUS", fact: "A colossal diplodocid with an absurdly long neck — engineering baffled and humans humbled.", wiki: "https://en.wikipedia.org/wiki/Supersaurus" },
  { name: "TALARURUS", fact: "A heavily armored ankylosaur with a broad body and defensive osteoderms.", wiki: "https://en.wikipedia.org/wiki/Talarurus" },
  { name: "TANIUS", fact: "A mid-sized hadrosauroid with a solid build found in Asia.", wiki: "https://en.wikipedia.org/wiki/Tanius" },
  { name: "TARBOSAURUS", fact: "A large Asian tyrannosaurid closely related to Tyrannosaurus and terrifying in its own right.", wiki: "https://en.wikipedia.org/wiki/Tarbosaurus" },
  { name: "TARCHIA", fact: "A stocky ankylosaur with heavy tail armor and a compact body for serious defense.", wiki: "https://en.wikipedia.org/wiki/Tarchia" },
  { name: "TELMATOSAURUS", fact: "A small hadrosaurid with unique features in its skull; a swamp-loving plant-eater.", wiki: "https://en.wikipedia.org/wiki/Telmatosaurus" },
  { name: "TENONTOSAURUS", fact: "A dependable mid-sized herbivore known from numerous North American fossils.", wiki: "https://en.wikipedia.org/wiki/Tenontosaurus" },
  { name: "THECODONTOSAURUS", fact: "An early dinosauriform important for understanding archosaur evolution.", wiki: "https://en.wikipedia.org/wiki/Thecodontosaurus" },
  { name: "THERIZINOSAURUS", fact: "A bizarre, giant-clawed herbivore with a long neck and a potbelly — one of the strangest theropods.", wiki: "https://en.wikipedia.org/wiki/Therizinosaurus" },
  { name: "THESCHELOSAURUS", fact: "A small ornithopod that thrived in Late Cretaceous North America.", wiki: "https://en.wikipedia.org/wiki/Thescelosaurus" },
  { name: "TOROSAURUS", fact: "A controversial ceratopsian closely related to Triceratops — debate still rages about its distinctness.", wiki: "https://en.wikipedia.org/wiki/Torosaurus" },
  { name: "TORVOSAURUS", fact: "A large, carnivorous Jurassic theropod — one of Europe’s top predators.", wiki: "https://en.wikipedia.org/wiki/Torvosaurus" },
  { name: "TRICERATOPS", fact: "A massive, three-horned herbivore with a huge frill used for display and defense.", wiki: "https://en.wikipedia.org/wiki/Triceratops" },
  { name: "TROODON", fact: "A smart, birdlike predator with keen senses and a large brain relative to body size.", wiki: "https://en.wikipedia.org/wiki/Troodon" },
  { name: "TSAGANTEGIA", fact: "A horned titan with a short frill — Mongolian deserts yielded many surprises.", wiki: "https://en.wikipedia.org/wiki/Tsagantegia" },
  { name: "TSINTAOSAURUS", fact: "A hadrosaur with a notable spike-like crest projecting from its forehead.", wiki: "https://en.wikipedia.org/wiki/Tsintaosaurus" },
  { name: "TUOJIANGOSAURUS", fact: "A well-armed stegosaur with tall plates and defensive spikes.", wiki: "https://en.wikipedia.org/wiki/Tuojiangosaurus" },
  { name: "TYLOCEPHALE", fact: "A pachycephalosaurid with a highly domed skull likely used in head-butting or display.", wiki: "https://en.wikipedia.org/wiki/Tylocephale" },
  { name: "TYRANNOSAURUS", fact: "The iconic apex predator with bone-crushing bite force and tiny forearms — king of the Cretaceous.", wiki: "https://en.wikipedia.org/wiki/Tyrannosaurus" },
  { name: "TYRANNOTITAN", fact: "A gigantic South American theropod and one of the largest known predators of its time.", wiki: "https://en.wikipedia.org/wiki/Tyrannotitan" },
  { name: "UDANOCERATOPS", fact: "A large ceratopsian with a massive frill known from Mongolia's Late Cretaceous.", wiki: "https://en.wikipedia.org/wiki/Udanoceratops" },
  { name: "UNENLAGIA", fact: "A South American dromaeosaurid linking raptors to bird evolution, with long arms and feathers.", wiki: "https://en.wikipedia.org/wiki/Unenlagia" },
  { name: "URBACODON", fact: "A poorly known small theropod named from fragmentary jaw remains.", wiki: "https://en.wikipedia.org/wiki/Urbacodon" },
  { name: "UTAHRAPTOR", fact: "THE ABSOLUTE RAPTORDAD. A hulking, clawed hunter the size of a bear with sickle claws built for ripping and theatrical kills. One of Emma's faves.", wiki: "https://en.wikipedia.org/wiki/Utahraptor" },
  { name: "VALDOSAURUS", fact: "An early Cretaceous ornithopod known from fragmentary remains in England.", wiki: "https://en.wikipedia.org/wiki/Valdosaurus" },
  { name: "VELOCIRAPTOR", fact: "A small, feathered dromaeosaur famous for its speed, intelligence, and deadly sickle claw.", wiki: "https://en.wikipedia.org/wiki/Velociraptor" },
  { name: "VULCANODON", fact: "One of the earliest large sauropods with a primitive body plan and robust limbs.", wiki: "https://en.wikipedia.org/wiki/Vulcanodon" },
  { name: "YANDUSAURUS", fact: "A small ornithopod from China that filled local ecological niches in the Early Cretaceous.", wiki: "https://en.wikipedia.org/wiki/Yandusaurus" },
  { name: "YANGCHUANOSAURUS", fact: "A Chinese carnivore with a powerful skull and strong jaws.", wiki: "https://en.wikipedia.org/wiki/Yangchuanosaurus" },
  { name: "YIMENOSAURUS", fact: "A sauropod genus known from fragmentary material in China.", wiki: "https://en.wikipedia.org/wiki/Yimenosaurus" },
  { name: "YINGSHANOSAURUS", fact: "A stegosaurs relative with plated armor — classic Jurassic silhouette.", wiki: "https://en.wikipedia.org/wiki/Yingshanosaurus" },
  { name: "YINLONG", fact: "A tiny, early ceratopsian that shows the humble beginnings of horned dinosaurs.", wiki: "https://en.wikipedia.org/wiki/Yinlong" },
  { name: "YUANMOUSAURUS", fact: "A lesser-known sauropod adding to the diversity of Asian giants.", wiki: "https://en.wikipedia.org/wiki/Yuanmousaurus" },
  { name: "YUNNANOSAURUS", fact: "A Chinese prosauropod that bridges the early phases of sauropod evolution.", wiki: "https://en.wikipedia.org/wiki/Yunnanosaurus" },
  { name: "YUTYRANNUS", fact: "A feathered tyrannosauroid demonstrating that big predators could be fuzzy — possibly used display feathers.", wiki: "https://en.wikipedia.org/wiki/Yutyrannus" },
  { name: "ZALMOXES", fact: "A Romanian hadrosauroid with a robust build and interesting skull anatomy.", wiki: "https://en.wikipedia.org/wiki/Zalmoxes" },
  { name: "ZEPHYROSAURUS", fact: "A small, nimble ornithopod known from fragmentary remains in North America.", wiki: "https://en.wikipedia.org/wiki/Zephyrosaurus" },
  { name: "ZUNICERATOPS", fact: "A small chasmosaurine ceratopsian notable as one of North America’s earliest horned dinosaurs.", wiki: "https://en.wikipedia.org/wiki/Zuniceratops" }
];

// === Dino Logic ===
function getDinoOfTheDay() {
  const today = new Date();
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000);
  const dino = dinoList[dayOfYear % dinoList.length];
  return dino;
}

function showDino() {
  const dino = getDinoOfTheDay();
  const container = document.getElementById("dino-info");
  if (dino) {
    container.innerHTML = `
      <h3>${dino.name.toUpperCase()}</h3>
      <p>${dino.fact}</p>
      <a href="${dino.wiki}" target="_blank">Learn More</a>
    `;
  } else {
    container.innerHTML = "<p>No dinosaur data available!</p>";
  }
}

document.addEventListener("DOMContentLoaded", showDino);
